<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDrivenTestSuiteREST</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>3ad10d5a-6400-43d2-a803-85de2007fa6c</testSuiteGuid>
   <testCaseLink>
      <guid>4316cebf-0e42-4684-baca-cff5ec26f4ff</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>f75f40ed-389e-4e24-beab-505708ceef71</id>
         <masked>false</masked>
         <name>username</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/DataDrivenDemoRESTTest</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>cb840ca5-5bb6-472f-84c2-6a7ad74fc189</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DataDrivenTestREST</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>cb840ca5-5bb6-472f-84c2-6a7ad74fc189</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>f75f40ed-389e-4e24-beab-505708ceef71</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
